[package]
name = "gladiastark"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = ">=2.9.2"
snforge_std = "0.35.1"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", edition = "2023_01" }
pragma_lib = { git = "https://github.com/astraly-labs/pragma-lib" }


[dev-dependencies]
snforge_std = { version = "0.35.1" }


[[target.starknet-contract]]
casm = true
sierra = true

[tool.fmt]
sort-module-level-items = false

[tool.snforge]
exit_first = false

